import {cp,mkdir,readFile,writeFile,rename} from 'node:fs/promises';
import {resolve,join} from 'node:path';
const root=resolve(import.meta.dirname,'..');
const output=join(root,'portable-builds',new Date().toISOString().replace(/[:.]/g,'-'),'Suivis chantier');
const appRoot=join(output,'resources','app');const ui=join(appRoot,'ui');
await mkdir(output,{recursive:true});await cp(join(root,'node_modules','electron','dist'),output,{recursive:true});
await rename(join(output,'electron.exe'),join(output,'Suivis chantier.exe'));
await mkdir(ui,{recursive:true});await mkdir(join(appRoot,'desktop'),{recursive:true});
for(const name of ['index.html','style.css','app.js','action-ui.js','model.js','postit.html','postit.js','postit-model.js','postit.css'])await cp(join(root,name),join(ui,name));
await cp(join(root,'icons'),join(ui,'icons'),{recursive:true});
await cp(join(root,'model.js'),join(appRoot,'model.js'));
for(const name of ['main.cjs','preload.cjs','file-store.js'])await cp(join(root,'desktop',name),join(appRoot,'desktop',name));
await cp(join(root,'desktop','renderer-store.js'),join(ui,'store.js'));await cp(join(root,'desktop','renderer-backup.js'),join(ui,'backup.js'));
await writeFile(join(appRoot,'package.json'),JSON.stringify({name:'suivis-chantier-portable',productName:'Suivis chantier',version:'1.1.0',type:'module',main:'desktop/main.cjs'}));
let html=await readFile(join(ui,'index.html'),'utf8');html=html.replace(/<link rel="manifest"[^>]*>/,'').replace('<title>Suivis chantier</title>','<title>Suivis chantier — Portable</title>');await writeFile(join(ui,'index.html'),html);
let js=await readFile(join(ui,'app.js'),'utf8');
js=js.replace('function backupModal(){','function browserBackupModal(){').replaceAll('↥ Sauvegarde & installation','↥ Sauvegarde & données').replace("if('serviceWorker'in navigator)","if(false&&'serviceWorker'in navigator)").replaceAll('Disponible hors connexion','Version Windows portable');
js+=`\nfunction backupModal(){modal('Sauvegarde & données',\`<div class="settings-block"><h3>Enregistrement automatique sur disque</h3><p>Chaque modification validée et chaque coche du Post-it sont écrites directement dans ton dossier. Tes chantiers et documents reviennent au lancement.</p><p id="backup-detail">\${esc(backupDescription())}</p><button data-desktop-show-folder>Ouvrir mon dossier de sauvegarde</button><p class="hint">suivis-chantier.json contient tes chantiers et toutes les pièces jointes. suivis-chantier.precedent.json conserve la version précédente. Ces fichiers restent sur ton PC.</p></div><div class="settings-block"><h3>Importer mes chantiers existants</h3><label class="upload">Importer ma sauvegarde JSON<input id="import-file" type="file" accept="application/json,.json"></label><p class="hint">Compatible avec les sauvegardes de la PWA. L’import remplace les chantiers présents après confirmation et les conserve ensuite automatiquement dans ton dossier.</p><button data-export>Exporter une copie supplémentaire</button></div><div class="settings-block"><h3>Version Windows portable</h3><p>Aucune installation. Ouvre Suivis chantier.exe depuis le dossier décompressé. Le dossier de données est mémorisé à côté de l’exécutable.</p><p>Les mails Zimbra se joignent en .eml, .msg ou .txt. Les raccourcis GIMA et véhicule ouvrent ton navigateur habituel.</p></div>\`);}\n`;
js+=`document.addEventListener('click',async event=>{const button=event.target.closest('button');if(!button)return;try{if(button.hasAttribute('data-desktop-show-folder'))await window.chantierDesktop.showFolder();if(button.hasAttribute('data-desktop-folder')){await window.chantierDesktop.chooseFolder();location.reload();}}catch(error){toast(error.message);}});\n`;
js=js.replace("<h1>Impossible d’ouvrir le stockage local</h1>","<h1>Impossible d’ouvrir le dossier des chantiers</h1>").replace('Vérifie que le navigateur autorise le stockage pour cette application, puis recharge la page.','Vérifie que ton dossier est accessible. Au premier lancement, choisis un dossier pour commencer.').replace('<p>Vérifie que ton dossier est accessible. Au premier lancement, choisis un dossier pour commencer.</p>','<p>Vérifie que ton dossier est accessible. Au premier lancement, choisis un dossier pour commencer.</p><button class="primary" data-desktop-folder>Choisir le dossier / Réessayer</button>');
await writeFile(join(ui,'app.js'),js);
let postit=await readFile(join(ui,'postit.js'),'utf8');
postit=postit.replace("export async function openPostit({simple=false,onOpen}={}) {","export async function openPostit({simple=false,onOpen}={}) {\n  if(window.chantierDesktop)return window.chantierDesktop.openPostit();");
postit=postit.replace('if(onOpen)onOpen();else window.open','if(window.chantierDesktop)window.chantierDesktop.openMain();else if(onOpen)onOpen();else window.open');
postit=postit.replace('Garde Suivis chantier ouvert, même réduit.','Le Post-it reste ouvert au premier plan, même si tu fermes la fenêtre principale.');
postit=postit.replace('mountPostit(document);','mountPostit(document,{pinned:true});');await writeFile(join(ui,'postit.js'),postit);
await cp(join(root,'desktop','LIRE-MOI.txt'),join(output,'LIRE-MOI.txt'));
await writeFile(join(root,'portable-builds','latest-build.json'),JSON.stringify({output,exe:join(output,'Suivis chantier.exe')}));
console.log(output);
